"Lint":
  stage: test
  image:
    name: registry.gitlab.com/hawk777/oc-wasm-ci-images/rust:6b6902e3b5880ae33b65ed516e410dc3e846f80e
  script:
    - cargo version
    - cargo clippy
    - cargo doc
    - cargo fmt -- --check
