"Lint":
  stage: test
  image:
    name: "rust"
  script:
    - rustup target add wasm32-unknown-unknown
    - rustup component add clippy rustfmt
    - cargo clippy
    - cargo doc
    - cargo fmt -- --check
