"Lint":
  stage: test
  image:
    name: registry.gitlab.com/hawk777/oc-wasm-ci-images/rust:ed2bd0679f7012ed3684a2787f053e2d230b16c9
  script:
    - cargo version
    - cargo clippy
    - cargo doc
    - cargo fmt -- --check
