[package]
name = "oc-wasm-helpers"
version = "0.12.0"
authors = ["Christopher Head <chead@chead.ca>"]
edition = "2021"
description = "Helpers used by multiple OC-Wasm high-level APIs"
repository = "https://gitlab.com/Hawk777/oc-wasm-helpers"
license = "GPL-3.0-only"
keywords = ["minecraft", "oc-wasm", "opencomputers"]
categories = ["games"]

[dependencies]
minicbor = { features = ["derive"], workspace = true }
oc-wasm-futures = { workspace = true }
oc-wasm-safe = { workspace = true }

[features]
default = ["alloc"]
alloc = []

[package.metadata.docs.rs]
default-target = "wasm32-unknown-unknown"
